### PR TITLE
always use filename if present

### LINKED ISSUE #102: Don't use STDIN if file name is provided even if not a TTY
When running `gql2ts` as part of certain task runners STDIN will not be a TTY.
This causes this code here:

https://github.com/avantcredit/gql2ts/blob/4e36bd52fc81a3c8fbffd5685a0a3933a3474f5b/packages/cli/src/index.ts#L64-L74

to read from STDIN even if a filename is provided, which ultimately will result in the hard-to-debug error
`GraphQLError: Syntax Error GraphQL request (1:1) Unexpected <EOF>`
because the STDIN is empty.

I would propose to always read from file when a file name is given.

### PR DESCRIPTION
**Pull request by brettjurgens**
fixes #102

### CODE REVIEW

**Comment by brettjurgens** [comment]
@felixfbecker i've tested this and it seems to work as intended. i've published a canary as `gql2ts@1.4.0-alpha.753be938`, would you mind testing it out?

File: packages/cli/src/index.ts [hunk 1]
```diff
@@ -62,17 +62,17 @@ const run: (schema: PossibleSchemaInput, options: Partial<ICLIOptions>) => void
...
+  const schema: string | object = readFile(fileName);
+  run(schema as PossibleSchemaInput, program as any);
+} else if (!process.stdin.isTTY) {
   let input: string = '';
   process.stdin.resume();
   process.stdin.setEncoding('utf8');
   process.stdin.on('data', (data) => {
     input += data;
   });
   process.stdin.on('end', () => run(safeJSONParse(input) as PossibleSchemaInput, program as any));
```
Comment (felixfbecker) [inline packages/cli/src/index.ts]: another improvement would be to have an `if` check here to check if `input` is empty and also print an error then.
